name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      SPRING_MAIN_BANNER-MODE: "off"
      DOCKER_BUILDKIT: "1"
      TESTCONTAINERS_RYUK_PRIVILEGED: "false"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'gradle'

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Build & Test
        run: ./gradlew clean test bootJar --no-daemon

      - name: Build Docker image
        run: docker build -t concert-backend:ci .
